apiVersion: v1
kind: PersistentVolume
metadata:
  name: devbox-pv
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 5Gi
  persistentVolumeReclaimPolicy: Retain
  # storageClassName: nfs

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: devbox-pvc
  # namespace: kube-system
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  # storageClassName: nfs
