apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: development-pvc
  # namespace: kube-system
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: devbox-pv
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 5Gi
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs
  nfs:
    path: /home/coast/Desktop/
    server: 172.16.31.31

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: devbox-pvc
  # namespace: kube-system
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: nfs
  