apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: webui-ingress
  namespace: default
  annotations:
    # k8s.kuboard.cn/displayName: webui
    # k8s.kuboard.cn/workload: webui
    kubernetes.io/ingress.class: 'traefik-internet'
    traefik.ingress.kubernetes.io/router.entrypoints: web,websecure
    traefik.ingress.kubernetes.io/router.middlewares:
      kube-system-http-redirect-https@kubernetescrd,
      kube-system-http-redirect-https-testing@kubernetescrd,
      kube-system-common-headers@kubernetescrd

spec:
  tls:
    - hosts:
        - '*.hk-testing.web3eye.io'
        - hk-testing.web3eye.io
      secretName: hk-testing-web3eye-io-tls
  rules:
    - host:
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: webui
                port:
                  number: 80
    # - host: www.hk-testing.web3eye.io
    #   http:
    #     paths:
    #       - path: /
    #         pathType: Prefix
    #         backend:
    #           service:
    #             name: webui
    #             port:
    #               number: 80
