version="0.0.1"

[nft-meta]
http-port=30100
grpc-port=30101
log-dir="/var/log"

[block-etl]
http-port=30110
grpc-port=30111
log-dir="/var/log"

[mysql]
ip="ct.mysql"
port=3306
user="root"
password="123123123"

[eth]
wallets="https://mainnet.infura.io/v3/03719c03f3bb46dda13decd1e58537f0"

[ipfs]
http-gateway="https://ipfs.io/"
