version="0.0.1"

[nft-meta]
ip="nft-meta"
http-port=30100
grpc-port=30101
log-file="/var/log/nft-meta.log"

[block-etl]
ip="block-etl"
http-port=30110
grpc-port=30111
log-file="/var/log/block-etl.log"

[cloud-proxy]
ip="cloud-proxy"
http-port=30120
grpc-port=30121
log-file="/var/log/cloud-proxy.log"

[gateway]
ip="gateway"
http-port=30130
grpc-port=30131
log-file="/var/log/gateway.log"

[ranker]
ip="ranker"
http-port=30140
grpc-port=30141
log-file="/var/log/ranker.log"

[entrance]
ip="entrance"
http-port=30150
grpc-port=30151
log-file="/var/log/entrance.log"

[gen-car]
ip="gen-car"
http-port=30160
grpc-port=30161
data-dir="/tmp/gencar_data"
log-file="/var/log/gen-car.log"

[dealer]
ip="dealer"
http-port=30160
grpc-port=30161
log-file="/var/log/dealer.log"

[image-converter]
address="http://image-converter:8080"
task-input-topic="image-converter-input"
task-output-topic="image-converter-output"

[mysql]
ip="mysql-headless"
port=3306
user="root"
password="QARo5aA6zO"
database="nft_meta"

[redis]
address="redis-cluster-headless:6379"
password="default"

[milvus]
address="milvus:19530"

[kafka]
bootstrap-servers="kafka-headless:9092"

[minio]
address="http://web3eye-minio:9000"
access-key="YacNyvYLuQ1J3mMaCvMy"
secret-key="AIYvh7F5TlzxagPySkD5flSIZhLGssZ432UKNqMJ"
region="default"
token-image-bucket="token-image-bucket"
token-image-car-bucket="token-image-car-bucket"


[eth]
wallets="https://mainnet.infura.io/v3/03719c03f3bb46dda13decd1e58537f0"

[ipfs]
http-gateway="https://ipfs.io/"
