# apiVersion: v1
# kind: PersistentVolume
# metadata:
#   namespace: kube-system
#   name: devbox-pv
# spec:
#   accessModes:
#     - ReadWriteMany
#   capacity:
#     storage: 10Gi
#   persistentVolumeReclaimPolicy: Retain
#   storageClassName: nfs
#   nfs:
#     path: /data/k8s_storage/cybertracer
#     server: 172.23.10.83

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: devbox-pvc
  namespace: kube-system
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  # storageClassName: nfs
