apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloud-proxy
  annotations:
    "sidecar.jaegertracing.io/inject": "true"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cloud-proxy
  template:
    metadata:
      labels:
        app: cloud-proxy
    spec:
      containers:
        - name: cloud-proxy
          # image: web3eye/cloud-proxy:latest
          image: coastlinesss/cloud-proxy:latest
          imagePullPolicy: Always
          volumeMounts:
            - name: service-config
              mountPath: /etc/CloudProxy
          env:
            - name: ENV_CLUSTER_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: mysql_password
              valueFrom:
                secretKeyRef:
                  name: mysql
                  key: mysql-root-password
            - name: redis_password
              valueFrom:
                secretKeyRef:
                  name: redis-cluster
                  key: redis-password
      volumes:
        - name: service-config
          configMap:
            name: cloud-proxy-config
---
apiVersion: v1
kind: Service
metadata:
  name: cloud-proxy
spec:
  ports:
    - name: http
      port: 30120
      targetPort: 30120
    - name: grpc
      port: 30121
      targetPort: 30121
    - name: healthz
      port: 30122
      targetPort: 30122
  selector:
    app: cloud-proxy
