apiVersion: apps/v1
kind: Deployment
metadata:
  name: block-etl
  # namespace: kube-system
  annotations:
    "sidecar.jaegertracing.io/inject": "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: block-etl
  template:
    metadata:
      labels:
        app: block-etl
    spec:
      containers:
        - name: block-etl
          image: coastlinesss/block-etl:latest
          imagePullPolicy: Always
          volumeMounts:
            - name: service-config
              mountPath: /etc/BlockETL
          env:
            # - name: ENV_ENVIRONMENT_TARGET
            #   valueFrom:
            #     configMapKeyRef:
            #       name: system-environment
            #       key: environment.target
            # - name: ENV_CONSUL_HOST
            #   valueFrom:
            #     configMapKeyRef:
            #       name: system-environment
            #       key: environment.consul_host
            # - name: ENV_CONSUL_PORT
            #   valueFrom:
            #     configMapKeyRef:
            #       name: system-environment
            #       key: environment.consul_port
            - name: ENV_CLUSTER_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
      volumes:
        - name: service-config
          configMap:
            name: block-etl-config
            items:
              - key: service-conf
                path: BlockETL.viper.yaml
---
apiVersion: v1
kind: Service
metadata:
  name: block-etl
  # namespace: kube-system
spec:
  selector:
    app: block-etl
  # clusterIP: None
  ports:
    - name: http
      port: 50490
      targetPort: 50490
    - name: grpc
      port: 50491
      targetPort: 50491
    - name: healthz
      port: 50493
      targetPort: 50493
    - name: prometheus
      port: 50492
      targetPort: 50492
