apiVersion: apps/v1
kind: Deployment
metadata:
  name: dealer
  # namespace: kube-system
  annotations:
    "sidecar.jaegertracing.io/inject": "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dealer
  template:
    metadata:
      labels:
        app: dealer
    spec:
      containers:
        - name: dealer
          image: coastlinesss/dealer:latest
          imagePullPolicy: Always
          volumeMounts:
            - name: service-config
              mountPath: /etc/BlockETL
          env:
            - name: ENV_CLUSTER_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: redis_password
              valueFrom:
                secretKeyRef:
                  name: redis-cluster
                  key: redis-password
      volumes:
        - name: service-config
          configMap:
            name: dealer-config
---
apiVersion: v1
kind: Service
metadata:
  name: dealer
  # namespace: kube-system
spec:
  selector:
    app: dealer
  # clusterIP: None
  ports:
    - name: http
      port: 50490
      targetPort: 50490
    - name: grpc
      port: 50491
      targetPort: 50491
